### ISSUE TITLE
name suggestions are with old rather than current name

### ISSUE THREAD

**Issue by JacobHeilmannClausen** [noque-lind/svampeatlas-ios#32]
If a species have presentation photos attached to an old synonym*, the AI or a manual name search returns the old synonym as suggested name suggestion without a photo. E.g. check Piptoporus betulinus (current name Fomitopsis betulina). Submitted by Jens H. Petersen

*I am unsure if this is the background for the issue, or if it rather has to do with the taxon tags in the AI (Jacob)

**Comment by noque-lind** [comment]
@JacobHeilmannClausen This has been fixed in current production version
